- name: Setup Apache
  hosts: webservers
  vars_files:
    - vars.yml

  tasks:
    - name: Install Apache and dependencies
      ansible.builtin.package:
        name:
          - apache2
          - libapache2-mod-php
        state: present
        update_cache: true

    - name: Set up Apache virtualhost
      ansible.builtin.template:
        src: "apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
        mode: "0644"

    - name: Enable new site
      ansible.builtin.command: a2ensite "{{ http_conf }}"
      changed_when: false
      notify: Restart apache

    - name: Disable default Apache site
      ansible.builtin.command: a2dissite 000-default.conf
      when: disable_default
      notify: Restart apache

    - name: Mod rewrite
      ansible.builtin.command: a2enmod rewrite
      changed_when: false
      notify: Restart apache

    - name: "UFW - Allow HTTP on port {{ http_port }}"
      community.general.ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted
