- name: Application configuration
  hosts: webservers
  vars_files:
    - vars.yml

  tasks:
    - name: Install PHP and dependencies
      ansible.builtin.package:
        name:
          - php{{ php_version }}
          - php{{ php_version }}-mbstring
          - php{{ php_version }}-xml
          - php{{ php_version }}-zip
          - php{{ php_version }}-mysql
          - php{{ php_version }}-xml
          - php{{ php_version }}-dev
          - php{{ php_version }}-pdo
          - php{{ php_version }}-gd
          - php{{ php_version }}-curl
          - unzip
        state: present
        update_cache: true

    - name: Download composer
      ansible.builtin.get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/installer
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        mode: "0755"

    - name: Run install script
      ansible.builtin.shell:
        cmd: cat /tmp/installer | php -- --install-dir=/usr/bin
      args:
        creates: /usr/bin/composer.phar

    - name: Move composer.phar -> composer
      ansible.builtin.command: mv /usr/bin/composer.phar /usr/bin/composer
      args:
        creates: /usr/bin/composer

    - name: Make composer executable
      ansible.builtin.file:
        path: /usr/bin/composer
        mode: u+x
        state: file

    - name: Pull Repo changes
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        force: true

    - name: Own {{ app_dir }}
      ansible.builtin.file:
        path: "{{ app_dir }}"
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        recurse: true

    - name: Setup environment variables
      ansible.builtin.template:
        src: ".env.j2"
        dest: "{{ app_dir }}/.env"
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        mode: "0666"

    - name: Set permissions for Laravel storage folder
      ansible.builtin.file:
        path: "{{ app_dir }}/storage"
        state: directory
        recurse: true
        mode: "0777"

    - name: Install composer dependencies
      ansible.builtin.shell: |
        set -o pipefail
        cd {{ app_dir }}
        export COMPOSER_ALLOW_SUPERUSER=1
        composer install --no-interaction
      changed_when: false
      args:
        executable: /bin/bash

    - name: Run Migrations with seed
      ansible.builtin.shell: |
        set -o pipefail
        cd {{ app_dir }}
        php artisan migrate:fresh --seed --force
      register: migrate_with_seed
      ignore_errors: true
      changed_when: false
      args:
        executable: /bin/bash

    - name: Run migrations without seed (fallback)
      ansible.builtin.command:
        cmd: php artisan migrate:fresh --force
        chdir: "{{ app_dir }}"
      when: migrate_with_seed is failed

    - name: Generate app key
      ansible.builtin.command:
        cmd: php artisan key:generate --force
        chdir: "{{ app_dir }}"
      register: gen_key_output
      changed_when: gen_key_output.rc == 0
