- name: Install generated SSL certificate
  hosts: webservers
  vars_files:
    - vars.yml

  tasks:
    - name: Set up Apache SSL virtualhost
      ansible.builtin.template:
        src: "apache-ssl.conf.j2"
        dest: "/etc/apache2/sites-available/ssl-{{ http_conf }}"
        mode: "0644"
      vars:
        cert_file: "{{ letsencrypt_certs_dir }}/{{ domain_name }}.crt"
        cert_key: "/etc/letsencrypt/keys/{{ domain_name }}.key"
        cert_chain: "{{ letsencrypt_certs_dir }}/chain_{{ domain_name }}.crt"

    - name: Enable SSL site conf
      ansible.builtin.command: a2ensite "ssl-{{ http_conf }}"
      changed_when: false
      register: enable_ssl_site
      notify: Restart apache

    - name: Enable Apache SSL module
      ansible.builtin.command: a2enmod ssl
      changed_when: false
      notify: Restart apache

    - name: Enable Apache Rewrite module
      ansible.builtin.command: a2enmod rewrite
      changed_when: false
      notify: Restart apache

    - name: Disable non-SSL site conf
      ansible.builtin.command: a2dissite "{{ http_conf }}"
      when: enable_ssl_site.rc == 0
      notify: Restart apache

    - name: "UFW - Allow HTTP on port 443"
      community.general.ufw:
        rule: allow
        port: "443"
        proto: tcp

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted
